name: Checks

on:
  push:
    branches:
      - "**"
  pull_request:
    types:
      - opened
      - synchronize # when a PR is updated
      - reopened # when a PR is reopened
      - ready_for_review # when a PR is ready for review
      - review_requested # when a PR is requested for review

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ["3.0", "3.4"]

    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Set up Ruby ${{ matrix.ruby-version }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true

      - name: Install
        run: |
          make install

      - name: Build
        run: |
          make build

      - name: Test
        run: |
          make test

      - uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"

      - name: Setup Featurevisor example-1 project
        run: |
          mkdir example-1
          (cd example-1 && npx @featurevisor/cli@2.x init --example=1)
          (cd example-1 && npm install)
          (cd example-1 && npx featurevisor test)

      - name: Run Featurevisor project tests against Ruby SDK
        run: ./bin/featurevisor test --projectDirectoryPath=./example-1
